# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Bay Jekyll Theme
description: Bay is a minimal Jekyll Theme.
baseurl: "/bay"
url: "https://cafepinson.github.io"
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"
remote_theme: eliottvincent/bay

header:
  pages:
    - name: Home: Korea
      slug: /
    - name: Work: Assistant professor
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: sujeongh@mokwon.ac.kr
    - type: wechat
      value: YourWeChatUsername
      link: "#"
  follow:
    - type: twitter
      name: Twitter
      link: http://twitter.com/YourTwitterUsername
      username: "@YourTwitterUsername"
    - type: facebook
      name: Facebook
      link: http://facebook.com/sujeonghong
    - type: linkedin
      name: LinkedIn
      link: http://linkedin.com/in/YourLinkedInUsername
    - type: github
      name: GitHub
      link: http://github.com/cafepinson
    - type: dribbble
      name: Dribbble
      link: https://dribbble.com/YourDribbbleUsername
    - type: rss
      name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

remote_theme: eliottvincent/bay
# Used for defeating caching
version: 1
